In [ ]:
import pandas as pd

data = pd.read_csv("/content/housing.csv")

description = data.describe()
print(description)

          longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000
mean    -119.569704     35.631861           28.639486   2635.763081
std        2.003532      2.135952           12.585558   2181.615252
min     -124.350000     32.540000            1.000000      2.000000
25%     -121.800000     33.930000           18.000000   1447.750000
50%     -118.490000     34.260000           29.000000   2127.000000
75%     -118.010000     37.710000           37.000000   3148.000000
max     -114.310000     41.950000           52.000000  39320.000000

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000
mean       537.870553   1425.476744    499.539680       3.870671
std        421.385070   1132.462122    382.329753       1.899822
min          1.000000      3.000000      1.000000       0.499900
25%        296.000000    787.000000    280.000000       2.563400
50%        435.000000   1166.000000    409.000000       3.534800
75%        647.000000   1725.000000    605.000000       4.743250
max       6445.000000  35682.000000   6082.000000      15.000100

       median_house_value
count        20640.000000
mean        206855.816909
std         115395.615874
min          14999.000000
25%         119600.000000
50%         179700.000000
75%         264725.000000
max         500001.000000

In [ ]:
data_types = data.dtypes

data_shape = data.shape

print("Data Types:\n", data_types)
print("\nData Shape:", data_shape)

Data Types:
 longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity        object
dtype: object

Data Shape: (20640, 10)

In [ ]:
nullcounts = data.isnull().sum()

data_filled = data.fillna(data.mean())

print("Null Value Counts:\n", nullcounts)

Null Value Counts:
 longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

<ipython-input-14-ad56c73e8e28>:3: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  data_filled = data.fillna(data.mean())

In [ ]:
X = data.drop(columns=["median_house_value"])
y = data["median_house_value"]

print("Features (X):\n", X.head())
print("\nTarget (y):\n", y.head())

Features (X):
    longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0
1    -122.22     37.86                21.0       7099.0          1106.0
2    -122.24     37.85                52.0       1467.0           190.0
3    -122.25     37.85                52.0       1274.0           235.0
4    -122.25     37.85                52.0       1627.0           280.0

   population  households  median_income ocean_proximity
0       322.0       126.0         8.3252        NEAR BAY
1      2401.0      1138.0         8.3014        NEAR BAY
2       496.0       177.0         7.2574        NEAR BAY
3       558.0       219.0         5.6431        NEAR BAY
4       565.0       259.0         3.8462        NEAR BAY

Target (y):
 0    452600.0
1    358500.0
2    352100.0
3    341300.0
4    342200.0
Name: median_house_value, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Train set shape:", X_train.shape)
print("Test set shape:", X_test.shape)

Train set shape: (16512, 9)
Test set shape: (4128, 9)

In [ ]:
nullvalues=data.isnull()
print(nullvalues)
t_mean=data.fillna(0)
print(t_mean)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0          False     False               False        False           False
1          False     False               False        False           False
2          False     False               False        False           False
3          False     False               False        False           False
4          False     False               False        False           False
...          ...       ...                 ...          ...             ...
20635      False     False               False        False           False
20636      False     False               False        False           False
20637      False     False               False        False           False
20638      False     False               False        False           False
20639      False     False               False        False           False

       population  households  median_income  median_house_value  \
0           False       False          False               False
1           False       False          False               False
2           False       False          False               False
3           False       False          False               False
4           False       False          False               False
...           ...         ...            ...                 ...
20635       False       False          False               False
20636       False       False          False               False
20637       False       False          False               False
20638       False       False          False               False
20639       False       False          False               False

       ocean_proximity
0                False
1                False
2                False
3                False
4                False
...                ...
20635            False
20636            False
20637            False
20638            False
20639            False

[20640 rows x 10 columns]
       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0
1        -122.22     37.86                21.0       7099.0          1106.0
2        -122.24     37.85                52.0       1467.0           190.0
3        -122.25     37.85                52.0       1274.0           235.0
4        -122.25     37.85                52.0       1627.0           280.0
...          ...       ...                 ...          ...             ...
20635    -121.09     39.48                25.0       1665.0           374.0
20636    -121.21     39.49                18.0        697.0           150.0
20637    -121.22     39.43                17.0       2254.0           485.0
20638    -121.32     39.43                18.0       1860.0           409.0
20639    -121.24     39.37                16.0       2785.0           616.0

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0
1          2401.0      1138.0         8.3014            358500.0
2           496.0       177.0         7.2574            352100.0
3           558.0       219.0         5.6431            341300.0
4           565.0       259.0         3.8462            342200.0
...           ...         ...            ...                 ...
20635       845.0       330.0         1.5603             78100.0
20636       356.0       114.0         2.5568             77100.0
20637      1007.0       433.0         1.7000             92300.0
20638       741.0       349.0         1.8672             84700.0
20639      1387.0       530.0         2.3886             89400.0

      ocean_proximity
0            NEAR BAY
1            NEAR BAY
2            NEAR BAY
3            NEAR BAY
4            NEAR BAY
...               ...
20635          INLAND
20636          INLAND
20637          INLAND
20638          INLAND
20639          INLAND

[20640 rows x 10 columns]

In [11]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

data = pd.read_csv('/content/housing.csv')
target_column = data.columns[-1]
features = data.drop(columns=[target_column])
target = data[target_column]
scaler = MinMaxScaler()
features_normalized = scaler.fit_transform(features)
features_normalized_df = pd.DataFrame(features_normalized, columns=features.columns)
print("Normalized Features:")
print(features_normalized_df.head())

Normalized Features:
   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0   0.211155  0.567481            0.784314     0.022331        0.019863
1   0.212151  0.565356            0.392157     0.180503        0.171477
2   0.210159  0.564293            1.000000     0.037260        0.029330
3   0.209163  0.564293            1.000000     0.032352        0.036313
4   0.209163  0.564293            1.000000     0.041330        0.043296

   population  households  median_income  median_house_value
0    0.008941    0.020556       0.539668            0.902266
1    0.067210    0.186976       0.538027            0.708247
2    0.013818    0.028943       0.466028            0.695051
3    0.015555    0.035849       0.354699            0.672783
4    0.015752    0.042427       0.230776            0.674638